### ISSUE TITLE
Error while running source code

### ISSUE THREAD

**Issue by worker8** [csgavino/Lollapalooza#1]
### Problem overview

When I compile the code I got a blank screen:

<img src="https://cloud.githubusercontent.com/assets/1988156/19720480/41195636-9ba9-11e6-9314-2f08669c7af2.png" width="250px"/>

However, if I use the sent apk, I am able to view the images:

<img src="https://cloud.githubusercontent.com/assets/1988156/19720869/eeb382ca-9baa-11e6-8308-8d54cffc2fb5.png" width="250px"/>

Can you help looking into this?

**Comment by csgavino** [comment]
@worker8 you need to set your Flickr API key for it to work. Take a look at build.properties.

**Comment by csgavino** [comment]
* gradle.properties
