### ISSUE TITLE
Implement loading indicator on First load and Load more

### ISSUE THREAD

**Issue by kittinunf** [csgavino/Lollapalooza#2]
It looks like you don't have loading indicator in place, when the network call is in progress. Also, it would be nice to see loading indicator when application is loading also next page.

Let's assume that this is a task that is assigned to you. Can you explain in detail here on how would you tackle it? Do you have an idea on how would you extend that functionality in your current codebase?

**Comment by csgavino** [comment]
Hi @kittinunf ,

‘first load’
I’d add a progress bar in fragment_photos.xml and logic in PhotosFragment’s onCompleted, and onError methods to toggle the bar’s visibility.

‘load more’
I’d see if I can figure out how to make the last row of the RecycleView display a progress bar. But I’m not sure if this is the ‘right’ approach as I’d be adding unnecessary noise to my DataSource.
